cmake_minimum_required(VERSION 3.16)
project(FragileTarnished LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "This project must be built for x64 architecture.")
endif()
add_library(${PROJECT_NAME} SHARED dllmain.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE psapi)
set_target_properties(${PROJECT_NAME} PROPERTIES OUTPUT_NAME "FragileTarnished" PREFIX "")
