local projname = "FragileTarnished"
workspace(projname)
architecture("x64")
configurations({ "Debug", "Release", "MinSizeRel" })
project(projname)
kind("SharedLib")
language("C++")
cppdialect("C++23")
cdialect("C23")
targetdir("bin/%{cfg.buildcfg}")
objdir("bin-int/%{cfg.buildcfg}")
files({ "src/**.h", "src/**.c", "src/**.cpp" })
multiprocessorcompile("On")
filter("configurations:Debug")
defines({ "_DEBUG" })
optimize("Off")
symbols("On")
staticruntime("Off")
runtime("Debug")
incrementallink("On")
filter("configurations:Release")
defines({ "NDEBUG" })
optimize("Size")
symbols("Off")
staticruntime("On")
runtime("Release")
incrementallink("Off")
linktimeoptimization("On")
filter("toolset:msc*")
buildoptions({ "/Ob2" })
linkoptions({ "/OPT:REF", "/OPT:ICF" })
filter("configurations:MinSizeRel")
defines({ "NDEBUG" })
optimize("Size")
filter("toolset:msc*")
buildoptions({ "/Ob1" })
symbols("Off")
staticruntime("Off")
runtime("Release")
incrementallink("Off")
linktimeoptimization("On")
filter("toolset:msc*")
linkoptions({ "/OPT:REF", "/OPT:ICF" })
filter({})
